### ISSUE TITLE
Extend description what EF Classic does.

### ISSUE THREAD

**Issue by MNF** [zzzprojects/EntityFramework-Classic#1]
The readme and http://entityframework-classic.net/ doesn’t clarify what EF Classic does and how it relates with your other projects, such as Entity Framework Extensions, Entity Framework Plus, Entity Framework Dynamic Filters, GraphDiff and Effort.

Also does “Built for developers by **Entity Framework developers**” means that you have Microsoft employees, who wrote/are writing  Microsoft Entity Framework? If not, please rephrase the statement to avoid ambiguity.

**Comment by JonathanMagnan** [comment]
Thank you for your feedback.

We will review it the Readme this week. We start to have quite a few features almost completed in development, so it will be a good time to update it.

---

> “Built for developers by Entity Framework developers” means that you have Microsoft employees, who wrote/are writing Microsoft Entity Framework

We don't have Microsoft employees. We will think about this statement as well this week.

**Comment by JonathanMagnan** [comment]
Hello @MNF ,

Just to let you known, the sentence has been replaced. You are right, the sentence was misleading.

The Readme will be updated soon to provide more information about our other products.

Here is a short resume
- **Entity Framework Extensions:** EF Classic will soon reference this library. It will offer for free `DeleteFromQuery` and `UpdateFromQuery` in the community version. Other features (`BulkSaveChanges` and `Bulk Operations`) will be part of the enterprise license.
- **Entity Framework Plus**: Most features will be imported into EF Classic. Since it's now possible to directly modify the source, we can go way beyond what `EF+` had to offer. We will continue to support `EF+`, but EF Classic will have his own features.
- **Entity Framework Dynamic Filter**: We are currently working to redo this feature. By modifying the source of EF6, it's now possible to overcome some limitations and do it better.
- **Graph Diff**: We are currently investigating it. We believe the code will be included in EF Classic via a shared project. So EF6 will benefit of change we do for EF Classic as well.
- **Effort**: Effort is already compatible with EF Classic (https://www.nuget.org/packages/Z.EntityFramework.Classic.Effort/)
- **Eval Expression**: EF Classic reference this project to offer for free LINQ Dynamic in the community version. Other features are part of the enterprise license.

**Comment by JonathanMagnan** [comment]
Hello @MNF ,

Just to let you know, the readme has been updated. We will for sure update it again soon to add more information.

Let me know if we can close this issue.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @MNF ,

This issue will be closed since it has been resolved.

Feel free to reopen it if you feel otherwise.

Best Regards,

Jonathan
