### ISSUE TITLE
Migrations?

### ISSUE THREAD

**Issue by kanadaj** [zzzprojects/EntityFramework-Classic#36]
Hello, are Migrations on your roadmap?

**Comment by JonathanMagnan** [comment]
Hello @kanadaj ,

Yes and no,

Microsoft is currently coding the version 6.3 which support .NET Standard and will eventually have Migration commands enabled.

So there is not really any value on our side to code it since when Microsoft will do it on their side. 

So supporting Migration for .NET Core is in our plan but once Microsoft completes it.

Meanwhile, we recommend creating a project in .NET Framework that is only used to create the migration script.

Let me know if that answers your question.

Best Regards,

Jonathan
