### ISSUE TITLE
this.Configuration not availalbe in .net core 6 for soft delete

### ISSUE THREAD

**Issue by kingsanu** [zzzprojects/EntityFramework-Classic#65]
I using your trial version of EF classic for soft delete, here i can't find this.Configuration.

![image](https://user-images.githubusercontent.com/47456495/202780756-ac6e7101-1425-48ce-8f49-2b1f8935e019.png)

don't know who's this issue from whose side?

===
Also plz let us know what we can do if we use database first approch, because all the time it removed when we scaffold from database first

**Comment by JonathanMagnan** [comment]
Hello @kingsanu ,

Do you think you could create a runnable project with the issue? It doesn’t need to be your project, just a new solution with the minimum code to reproduce the issue.

We have an example online in .NET6, so I'm not sure to understand what is missing: https://dotnetfiddle.net/dnuxaL

With your second question, we currently believe you are using EF6 with EF Classic but that's one or other since EF Classic is a fork of EF6.

**Comment by kingsanu** [comment]
I'm sorry to let you know that i'm using .net core 6 with EF core, so this.Configuration is not availalbe here.

**Comment by JonathanMagnan** [comment]
Hello @kingsanu ,

Unfortunately, you cannot use EF Classic if you are using EF Core. So indeed, this configuration is not available in your case.

Best Regards,

Jon
